# enter original string here between triple quotes
str0 = """
[{"name":"transaction_id","description":"","type":"string","mode":"NULLABLE"},{"name":"order_order_id","description":"","type":"string","mode":"NULLABLE"},{"name":"order_vendor_id","description":"","type":"string","mode":"NULLABLE"},{"name":"order_vendor","description":"","type":"string","mode":"NULLABLE"},{"name":"order_po_number","description":"","type":"string","mode":"NULLABLE"},{"name":"order_cust_order_number","description":"","type":"string","mode":"NULLABLE"},{"name":"order_billtopp_address1","description":"","type":"string","mode":"NULLABLE"},{"name":"order_billtopp_address2","description":"","type":"string","mode":"NULLABLE"},{"name":"order_billtopp_address3","description":"","type":"string","mode":"NULLABLE"},{"name":"order_billtopp_city","description":"","type":"string","mode":"NULLABLE"},{"name":"order_billtopp_country","description":"","type":"string","mode":"NULLABLE"},{"name":"order_billtopp_county","description":"","type":"string","mode":"NULLABLE"},{"name":"order_billtopp_customer_number","description":"","type":"string","mode":"NULLABLE"},{"name":"order_billto_day_phone","description":"","type":"string","mode":"NULLABLE"},{"name":"order_billto_email","description":"","type":"string","mode":"NULLABLE"},{"name":"order_billto_evening_phone","description":"","type":"string","mode":"NULLABLE"},{"name":"order_billto_first_name","description":"","type":"string","mode":"NULLABLE"},{"name":"order_billto_last_name","description":"","type":"string","mode":"NULLABLE"},{"name":"order_billto_name","description":"","type":"string","mode":"NULLABLE"},{"name":"order_billto_postal_code","description":"","type":"string","mode":"NULLABLE"},{"name":"order_billto_postal_code_ext","description":"","type":"string","mode":"NULLABLE"},{"name":"order_billto_state","description":"","type":"string","mode":"NULLABLE"},{"name":"order_close_date","description":"","type":"timestamp","mode":"NULLABLE"},{"name":"order_close_datetime","description":"","type":"timestamp","mode":"NULLABLE"},{"name":"order_order_control_number","description":"","type":"string","mode":"NULLABLE"},{"name":"order_customer_addr1","description":"","type":"string","mode":"NULLABLE"},{"name":"order_customer_addr2","description":"","type":"string","mode":"NULLABLE"},{"name":"order_customer_addr3","description":"","type":"string","mode":"NULLABLE"},{"name":"order_customer_city","description":"","type":"string","mode":"NULLABLE"},{"name":"order_customer_county","description":"","type":"string","mode":"NULLABLE"},{"name":"order_customer_country","description":"","type":"string","mode":"NULLABLE"},{"name":"order_customer_day_phone","description":"","type":"string","mode":"NULLABLE"},{"name":"order_customer_email","description":"","type":"string","mode":"NULLABLE"},{"name":"order_customer_night_phone","description":"","type":"string","mode":"NULLABLE"},{"name":"order_customer_name1","description":"","type":"string","mode":"NULLABLE"},{"name":"order_customer_name2","description":"","type":"string","mode":"NULLABLE"},{"name":"order_customer_name","description":"","type":"string","mode":"NULLABLE"},{"name":"order_customer_order_number","description":"","type":"string","mode":"NULLABLE"},{"name":"order_customer_postal_code","description":"","type":"string","mode":"NULLABLE"},{"name":"order_customer_postal_code_ext","description":"","type":"string","mode":"NULLABLE"},{"name":"order_customer_state","description":"","type":"string","mode":"NULLABLE"},{"name":"order_download_date","description":"","type":"timestamp","mode":"NULLABLE"},{"name":"order_download_datetime","description":"","type":"timestamp","mode":"NULLABLE"},{"name":"order_handling","description":"","type":"string","mode":"NULLABLE"},{"name":"order_insert_date","description":"","type":"timestamp","mode":"NULLABLE"},{"name":"order_line_count","description":"","type":"string","mode":"NULLABLE"},{"name":"order_merchandise","description":"","type":"string","mode":"NULLABLE"},{"name":"order_vendor_name","description":"","type":"string","mode":"NULLABLE"},{"name":"order_order_date","description":"","type":"timestamp","mode":"NULLABLE"},{"name":"order_payment_method","description":"","type":"string","mode":"NULLABLE"},{"name":"order_sales_division_name","description":"","type":"string","mode":"NULLABLE"},{"name":"order_shipping_code_name","description":"","type":"string","mode":"NULLABLE"},{"name":"order_shipping","description":"","type":"string","mode":"NULLABLE"},{"name":"order_shipto_address1","description":"","type":"string","mode":"NULLABLE"},{"name":"order_shipto_address2","description":"","type":"string","mode":"NULLABLE"},{"name":"order_shipto_address3","description":"","type":"string","mode":"NULLABLE"},{"name":"order_shipto_city","description":"","type":"string","mode":"NULLABLE"},{"name":"order_order_status","description":"","type":"string","mode":"NULLABLE"},{"name":"order_shipto_country","description":"","type":"string","mode":"NULLABLE"},{"name":"order_shipto_customer_number","description":"","type":"string","mode":"NULLABLE"},{"name":"shipto_day_phone","description":"","type":"string","mode":"NULLABLE"},{"name":"shipto_email","description":"","type":"string","mode":"NULLABLE"},{"name":"shipto_evening_phone","description":"","type":"string","mode":"NULLABLE"},{"name":"shipto_name1","description":"","type":"string","mode":"NULLABLE"},{"name":"shipto_name2","description":"","type":"string","mode":"NULLABLE"},{"name":"shipto_name","description":"","type":"string","mode":"NULLABLE"},{"name":"shipto_postal_code","description":"","type":"string","mode":"NULLABLE"},{"name":"shipto_postal_code_ext","description":"","type":"string","mode":"NULLABLE"},{"name":"shipto_state","description":"","type":"string","mode":"NULLABLE"},{"name":"order_substatus","description":"","type":"string","mode":"NULLABLE"},{"name":"order_subtotal","description":"","type":"string","mode":"NULLABLE"},{"name":"order_tax","description":"","type":"string","mode":"NULLABLE"},{"name":"order_total","description":"","type":"string","mode":"NULLABLE"},{"name":"line_product_color","description":"","type":"string","mode":"NULLABLE"},{"name":"line_product_description","description":"","type":"string","mode":"NULLABLE"},{"name":"line_description2","description":"","type":"string","mode":"NULLABLE"},{"name":"line_expected_ship_date","description":"","type":"timestamp","mode":"NULLABLE"},{"name":"line_expected_ship_datetime","description":"","type":"timestamp","mode":"NULLABLE"},{"name":"line_merchant_line_number","description":"","type":"string","mode":"NULLABLE"},{"name":"line_merchant_productid","description":"","type":"string","mode":"NULLABLE"},{"name":"line_merchant_sku","description":"","type":"string","mode":"NULLABLE"},{"name":"line_order_line_number","description":"","type":"string","mode":"NULLABLE"},{"name":"line_product_group","description":"","type":"string","mode":"NULLABLE"},{"name":"line_qty_ordered","description":"","type":"string","mode":"NULLABLE"},{"name":"line_requested_arrival_date","description":"","type":"timestamp","mode":"NULLABLE"},{"name":"line_requested_arrival_datetime","description":"","type":"timestamp","mode":"NULLABLE"},{"name":"order_ship_method","description":"","type":"string","mode":"NULLABLE"},{"name":"line_lineitem_status","description":"","type":"string","mode":"NULLABLE"},{"name":"line_vendor_sku","description":"","type":"string","mode":"NULLABLE"},{"name":"line_shipping_cart_sku","description":"","type":"string","mode":"NULLABLE"},{"name":"line_prodsize","description":"","type":"string","mode":"NULLABLE"},{"name":"line_unit_cost","description":"","type":"string","mode":"NULLABLE"},{"name":"line_unit_of_measure","description":"","type":"string","mode":"NULLABLE"},{"name":"line_unit_price","description":"","type":"string","mode":"NULLABLE"},{"name":"line_upc","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_transaction_action","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_applied_date","description":"","type":"timestamp","mode":"NULLABLE"},{"name":"transaction_backorder_date","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_cancel_date","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_cancel_reason_desc","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_invoice_credit_adj","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_estimated_delivery_date","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_estimated_ship_date","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_invoice_date","description":"","type":"timestamp","mode":"NULLABLE"},{"name":"transaction_invoice_handling","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_invoice_number","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_invoice_shipping","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_invoice_tax","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_invoice_total","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_return_date","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_return_reason_desc","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_ship_date","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_ship_method_description","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_tracking_number","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_ssccid_container_label","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_sscc_auto_populate","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_invoice_unit_cost","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_line_merchandise","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_line_shipping","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_line_subtotal","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_line_tax","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_line_misc_charges","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_transaction_quantity","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_transaction_upc","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_backorder_reason","description":"","type":"string","mode":"NULLABLE"},{"name":"transaction_backorder_description","description":"","type":"string","mode":"NULLABLE"},{"name":"city","description":"","type":"string","mode":"NULLABLE"},{"name":"state","description":"","type":"string","mode":"NULLABLE"},{"name":"postal_code","description":"","type":"string","mode":"NULLABLE"},{"name":"file_name","description":"","type":"string","mode":"NULLABLE"},{"name":"last_upd_snsh_id","description":"","type":"string","mode":"NULLABLE"},{"name":"last_upd_ts","description":"","type":"timestamp","mode":"NULLABLE"},{"name":"load_dt","description":"","type":"date","mode":"NULLABLE"}]
"""

# add line breaks 
str1 = str0.replace("},","},\n")

# change all values to uppercase
str2 = str1.upper()

# all non column names back to lower case
backToLower = [""""NAME":""", """"DESCRIPTION":""", """TYPE":"STRING""", """TYPE":"DATE""", """TYPE":"TIMESTAMP""", """MODE":"""]
for i in backToLower:
	str2 = str2.replace(i, i.lower())


print '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
print str2
print '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'

# OUTPUT
# [{"name":"TRANSACTION_ID","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_ORDER_ID","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_VENDOR_ID","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_VENDOR","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_PO_NUMBER","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_CUST_ORDER_NUMBER","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_BILLTOPP_ADDRESS1","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_BILLTOPP_ADDRESS2","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_BILLTOPP_ADDRESS3","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_BILLTOPP_CITY","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_BILLTOPP_COUNTRY","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_BILLTOPP_COUNTY","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_BILLTOPP_CUSTOMER_NUMBER","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_BILLTO_DAY_PHONE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_BILLTO_EMAIL","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_BILLTO_EVENING_PHONE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_BILLTO_FIRST_NAME","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_BILLTO_LAST_NAME","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_BILLTO_NAME","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_BILLTO_POSTAL_CODE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_BILLTO_POSTAL_CODE_EXT","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_BILLTO_STATE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_CLOSE_DATE","description":"","type":"timestamp","mode":"NULLABLE"},
# {"name":"ORDER_CLOSE_DATETIME","description":"","type":"timestamp","mode":"NULLABLE"},
# {"name":"ORDER_ORDER_CONTROL_NUMBER","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_CUSTOMER_ADDR1","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_CUSTOMER_ADDR2","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_CUSTOMER_ADDR3","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_CUSTOMER_CITY","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_CUSTOMER_COUNTY","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_CUSTOMER_COUNTRY","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_CUSTOMER_DAY_PHONE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_CUSTOMER_EMAIL","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_CUSTOMER_NIGHT_PHONE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_CUSTOMER_NAME1","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_CUSTOMER_NAME2","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_CUSTOMER_NAME","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_CUSTOMER_ORDER_NUMBER","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_CUSTOMER_POSTAL_CODE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_CUSTOMER_POSTAL_CODE_EXT","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_CUSTOMER_STATE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_DOWNLOAD_DATE","description":"","type":"timestamp","mode":"NULLABLE"},
# {"name":"ORDER_DOWNLOAD_DATETIME","description":"","type":"timestamp","mode":"NULLABLE"},
# {"name":"ORDER_HANDLING","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_INSERT_DATE","description":"","type":"timestamp","mode":"NULLABLE"},
# {"name":"ORDER_LINE_COUNT","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_MERCHANDISE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_VENDOR_NAME","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_ORDER_DATE","description":"","type":"timestamp","mode":"NULLABLE"},
# {"name":"ORDER_PAYMENT_METHOD","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_SALES_DIVISION_NAME","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_SHIPPING_CODE_NAME","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_SHIPPING","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_SHIPTO_ADDRESS1","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_SHIPTO_ADDRESS2","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_SHIPTO_ADDRESS3","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_SHIPTO_CITY","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_ORDER_STATUS","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_SHIPTO_COUNTRY","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_SHIPTO_CUSTOMER_NUMBER","description":"","type":"string","mode":"NULLABLE"},
# {"name":"SHIPTO_DAY_PHONE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"SHIPTO_EMAIL","description":"","type":"string","mode":"NULLABLE"},
# {"name":"SHIPTO_EVENING_PHONE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"SHIPTO_NAME1","description":"","type":"string","mode":"NULLABLE"},
# {"name":"SHIPTO_NAME2","description":"","type":"string","mode":"NULLABLE"},
# {"name":"SHIPTO_NAME","description":"","type":"string","mode":"NULLABLE"},
# {"name":"SHIPTO_POSTAL_CODE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"SHIPTO_POSTAL_CODE_EXT","description":"","type":"string","mode":"NULLABLE"},
# {"name":"SHIPTO_STATE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_SUBSTATUS","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_SUBTOTAL","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_TAX","description":"","type":"string","mode":"NULLABLE"},
# {"name":"ORDER_TOTAL","description":"","type":"string","mode":"NULLABLE"},
# {"name":"LINE_PRODUCT_COLOR","description":"","type":"string","mode":"NULLABLE"},
# {"name":"LINE_PRODUCT_DESCRIPTION","description":"","type":"string","mode":"NULLABLE"},
# {"name":"LINE_DESCRIPTION2","description":"","type":"string","mode":"NULLABLE"},
# {"name":"LINE_EXPECTED_SHIP_DATE","description":"","type":"timestamp","mode":"NULLABLE"},
# {"name":"LINE_EXPECTED_SHIP_DATETIME","description":"","type":"timestamp","mode":"NULLABLE"},
# {"name":"LINE_MERCHANT_LINE_NUMBER","description":"","type":"string","mode":"NULLABLE"},
# {"name":"LINE_MERCHANT_PRODUCTID","description":"","type":"string","mode":"NULLABLE"},
# {"name":"LINE_MERCHANT_SKU","description":"","type":"string","mode":"NULLABLE"},
# {"name":"LINE_ORDER_LINE_NUMBER","description":"","type":"string","mode":"NULLABLE"},
# {"name":"LINE_PRODUCT_GROUP","description":"","type":"string","mode":"NULLABLE"},
# {"name":"LINE_QTY_ORDERED","description":"","type":"string","mode":"NULLABLE"},
# {"name":"LINE_REQUESTED_ARRIVAL_DATE","description":"","type":"timestamp","mode":"NULLABLE"},
# {"name":"LINE_REQUESTED_ARRIVAL_DATETIME","description":"","type":"timestamp","mode":"NULLABLE"},
# {"name":"ORDER_SHIP_METHOD","description":"","type":"string","mode":"NULLABLE"},
# {"name":"LINE_LINEITEM_STATUS","description":"","type":"string","mode":"NULLABLE"},
# {"name":"LINE_VENDOR_SKU","description":"","type":"string","mode":"NULLABLE"},
# {"name":"LINE_SHIPPING_CART_SKU","description":"","type":"string","mode":"NULLABLE"},
# {"name":"LINE_PRODSIZE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"LINE_UNIT_COST","description":"","type":"string","mode":"NULLABLE"},
# {"name":"LINE_UNIT_OF_MEASURE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"LINE_UNIT_PRICE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"LINE_UPC","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_TRANSACTION_ACTION","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_APPLIED_DATE","description":"","type":"timestamp","mode":"NULLABLE"},
# {"name":"TRANSACTION_BACKORDER_DATE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_CANCEL_DATE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_CANCEL_REASON_DESC","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_INVOICE_CREDIT_ADJ","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_ESTIMATED_DELIVERY_DATE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_ESTIMATED_SHIP_DATE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_INVOICE_DATE","description":"","type":"timestamp","mode":"NULLABLE"},
# {"name":"TRANSACTION_INVOICE_HANDLING","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_INVOICE_NUMBER","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_INVOICE_SHIPPING","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_INVOICE_TAX","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_INVOICE_TOTAL","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_RETURN_DATE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_RETURN_REASON_DESC","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_SHIP_DATE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_SHIP_METHOD_DESCRIPTION","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_TRACKING_NUMBER","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_SSCCID_CONTAINER_LABEL","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_SSCC_AUTO_POPULATE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_INVOICE_UNIT_COST","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_LINE_MERCHANDISE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_LINE_SHIPPING","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_LINE_SUBTOTAL","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_LINE_TAX","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_LINE_MISC_CHARGES","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_TRANSACTION_QUANTITY","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_TRANSACTION_UPC","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_BACKORDER_REASON","description":"","type":"string","mode":"NULLABLE"},
# {"name":"TRANSACTION_BACKORDER_DESCRIPTION","description":"","type":"string","mode":"NULLABLE"},
# {"name":"CITY","description":"","type":"string","mode":"NULLABLE"},
# {"name":"STATE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"POSTAL_CODE","description":"","type":"string","mode":"NULLABLE"},
# {"name":"FILE_NAME","description":"","type":"string","mode":"NULLABLE"},
# {"name":"LAST_UPD_SNSH_ID","description":"","type":"string","mode":"NULLABLE"},
# {"name":"LAST_UPD_TS","description":"","type":"timestamp","mode":"NULLABLE"},
# {"name":"LOAD_DT","description":"","type":"date","mode":"NULLABLE"}]