# enter original string here between triple quotes
str0 = """ORDER_ID	STRING	NULLABLE	
Describe this field...
BOOLEAN_LINE_NUMBER	STRING	NULLABLE	
Describe this field...
VENDOR_SKU	STRING	NULLABLE	
Describe this field...
MERCHANT_SKU	STRING	NULLABLE	
Describe this field...
ORDER_DOWNLOAD_DATETIME	TIMESTAMP	NULLABLE	
Describe this field...
ORDER_LINE_COUNT	STRING	NULLABLE	
Describe this field...
VENDOR_ID	STRING	NULLABLE	
Describe this field...
VENDOR	STRING	NULLABLE	
Describe this field...
CUSTOMER_ORDER_NUMBER	STRING	NULLABLE	
Describe this field...
PO_NUMBER	STRING	NULLABLE	
Describe this field...
SHOPPING_CART_SKU	STRING	NULLABLE	
Describe this field...
ORDER_DATE	TIMESTAMP	NULLABLE	
Describe this field...
CUSTOMER_INSERT_DATE	TIMESTAMP	NULLABLE	
Describe this field...
STATUS	STRING	NULLABLE	
Describe this field...
SUBSTATUS	STRING	NULLABLE	
Describe this field...
LINE_STATUS	STRING	NULLABLE	
Describe this field...
DESCRIPTION	STRING	NULLABLE	
Describe this field...
QUANTITY_ORDERED	STRING	NULLABLE	
Describe this field...
UNIT_COST	STRING	NULLABLE	
Describe this field...
UNIT_OF_MEASURE	STRING	NULLABLE	
Describe this field...
CUSTOMER_ORDER_DATE	TIMESTAMP	NULLABLE	
Describe this field...
CUSTOMER_NUMBER	STRING	NULLABLE	
Describe this field...
SHIP_TO_CITY	STRING	NULLABLE	
Describe this field...
SHIP_TO_POSTALCODE	STRING	NULLABLE	
Describe this field...
SHIP_TO_STATE	STRING	NULLABLE	
Describe this field...
PRIORITY	STRING	NULLABLE	
Describe this field...
FILE_NAME	STRING	NULLABLE	
Describe this field...
LAST_UPD_SNSH_ID	STRING	NULLABLE	
Describe this field...
LAST_UPD_TS	TIMESTAMP	NULLABLE	
Describe this field...
LOAD_DT	DATE	NULLABLE	
Describe this field...
"""
 
# remove all unwanted strings and values
nullVals = ["INTEGER	NULLABLE", "STRING	NULLABLE", "FLOAT	NULLABLE", "TIMESTAMP	NULLABLE", "BOOLEAN	NULLABLE", "DATE	NULLABLE", "Describe this field...", " ", "	"]
for i in nullVals:
    str0 = str0.replace(i, "")
 
# replace all paragraph breaks with commas
newStr = str0. replace("\n", ",")
newStr1 = newStr. replace(",,", ", ")
 
# change all values to uppercase
finalStr = newStr1.upper()
print '------------------------------------------------------------'
print finalStr
 
# removes last 2 characters (space and last comma)
print '------------------------------------------------------------'
print finalStr[:-2]
 
# result
# ORDER_ID, BOOLEAN_LINE_NUMBER, VENDOR_SKU, MERCHANT_SKU, ORDER_DOWNLOAD_DATETIME, ORDER_LINE_COUNT, VENDOR_ID, VENDOR, CUSTOMER_ORDER_NUMBER, PO_NUMBER, SHOPPING_CART_SKU, ORDER_DATE, CUSTOMER_INSERT_DATE, STATUS, SUBSTATUS, LINE_STATUS, DESCRIPTION, QUANTITY_ORDERED, UNIT_COST, UNIT_OF_MEASURE, CUSTOMER_ORDER_DATE, CUSTOMER_NUMBER, SHIP_TO_CITY, SHIP_TO_POSTALCODE, SHIP_TO_STATE, PRIORITY, FILE_NAME, LAST_UPD_SNSH_ID, LAST_UPD_TS, LOAD_DT
